---
title: "Tutorial 5a Solution"
subtitle: "Pattern Recognition"
author: "Markus Löning, Simon Weiß & Tamara Bogatzki"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---
### Exercise 1d.e
The solution region is the skyblue region between the green and blue line. Explanation: The lines represent the boundaries of the given restrictions (the inequalities). For $g(x) \geq 0$ points on the line are part of the solution.
```{r, eval=FALSE}
a2=3
a1=4

rest1 = function(a1){a2=a1}
rest2= function(a1){a2=a1/2}
rest3 = function(a1){a2=-a1}
rest4 = function(a1){a2=(-3/4)*a1}

curve(rest1, from = -100, to = 100,  xlab="x", ylab="y", col="red", lwd=2);
curve(rest2, from = -100, to = 100, col="blue", lwd=2, add=TRUE)
curve(rest3, col="yellow", lwd=2, add=TRUE)
curve(rest4, col="green", lwd=2, add=TRUE)

cord.x <- c(-100,-100,0)
cord.y <- c((-3/4)*-100,0,0)
cord.y2 <- c(-50,0,0)
polygon(cord.x, cord.y, col="skyblue")
polygon(cord.x, cord.y2, col = "skyblue")

```


### Exercise 2d
```{r, eval=FALSE}
#sample data
x1 <- 3 
x2 <- 1 
x3 <- -2 

#normalise data
x3 <- -x3

#x vector
y <- matrix(c(1, 1, 1, x1, x2, x3), ncol=3, byrow = TRUE)
y
```


### Exercise 2e
```{r, eval=FALSE}
perceptron.fun <- function(x, a0, eta){
  a <- a0  #Set weighting matrix to initial input
  J <- 1  #Set cost uequal to zero
  num_iter <- 1
  
  while(J != 0){
    g <- t(a) %*% y
    a <- a + eta * rowSums(as.matrix(y[, which(g<0)]))
    J <- sum(-g[which(g<0)])
    J_hist[num_iter+1] <- J
    num_iter <- num_iter + 1
  }
 return(list(weight_vec=a, J=J, J_hist = J_hist, num_iter = num_iter))
}
  

#Estimation
a0 <- cbind(c(1,-4))  # Initial weight vector

perceptron_est <- perceptron.fun(y, a0, eta=0.1)
  
```

